version: '3.1'
services:
  db:
    container_name: db
    image: mpostgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
#    volumes:
#      - ./data:/var/lib/mysql
  rails:
    container_name: rails
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_PASSWORD: elfxf
    volumes:
      - ./blog-api:/blog-api
    ports:
      - "3000:3000"
    depends_on:
      - db
